---
#- name: Load tasks from asdf.yml
#  import_tasks: asdf.yml
#
#- name: Load tasks from mecab.yml
#  import_tasks: mecab.yml
#
#- name: Load tasks from mongodb.yml
#  import_tasks: mongodb.yml
#
#- name: Load tasks from shirasagi.yml
#  import_tasks: shirasagi.yml
#
#- name: Load tasks from jtalk.yml
#  import_tasks: jtalk.yml

- name: Load tasks from nginx.yml
  import_tasks: nginx.yml
